source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DYSRootViewController_Example', :exclusive => true do
  pod "DYSRootViewController", :path => "../"
end

target 'DYSRootViewController_Tests', :exclusive => true do
  pod "DYSRootViewController", :path => "../"

  pod 'FBSnapshotTestCase'
end
